import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import Navigation from "@/components/Navbar";
import "./globals.css";

import { cn } from "@/lib/utils"
import Sidebar from "@/components/Sidebar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Echo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "flex font-sans bg-neutral-100",
        fontSans.variable
      )}>
        <Navigation />
        {/* <main className="flex flex-col items-center justify-center"> */}
        {children}
        {/* </main> */}
      </body>
    </html>
  );
}
